### ISSUE TITLE
Use of GPL code is incompatible with Apache License

### ISSUE THREAD

**Issue by lederernc** [gvinciguerra/PGM-index#10]
The sdsl library is licensed under the GPL v3 license. You cannot use code with that license in this library without explicit permission from the owner of that library as the terms are incompatible.

**Comment by darko20** [comment]
The problem can be solved by dual licencing PGM-index under Apache and GPL. Also alglib is GPL'd in the tuner directory.

The better solution is to remove the dependency on the GPL'd code by re-implementing the required functionality or finding it elsewhere with less restrictive licencing.

**Comment by mpetri** [comment]
There is actually a version of SDSL that is BSD licensed but the authors kind of gave up on this midway into this project: https://github.com/xxsds/sdsl-lite/blob/master/LICENSE so it was never released as "version 3".

**Comment by gvinciguerra** [comment]
Thanks @lederernc for pointing out the problem, and thanks @darko20 and @mpetri for suggesting solutions.

I switched to the BSD-licensed SDSL, as @mpetri suggested. For alglib, I agree with @darko20 that it would be better to remove the dependency. I'll search if there are any lightweight libraries for nonlinear least-squares fitting with an Apache-compatible license.

**Comment by data-man** [comment]
> lightweight libraries for nonlinear least-squares fitting with an Apache-compatible license.

https://github.com/Rookfighter/least-squares-cpp (MIT License, header-only).
But [Eigen3](https://gitlab.com/libeigen/eigen) (MPL2, header-only) is required.

**Comment by gvinciguerra** [comment]
Thanks @data-man for suggesting an alternative library.

I ended up implementing a custom fit function on linearised data, and I removed the alglib dependency.
