### ISSUE TITLE
MacOS aarch64 compile issue

### ISSUE THREAD

**Issue by chadbrewbaker** [gvinciguerra/PGM-index#12]
Apple clang version 12.0.0 (clang-1200.0.32.28)

Guessing this is an X86 dependency that should be #ifdef guarded? I'll take a look tomorrow.

PGM-index/include/pgm/piecewise_linear_model.hpp:27:9: warning: Compilation with -fopenmp is optional but recommended [-W#pragma-messages]
#pragma message ("Compilation with -fopenmp is optional but recommended")
        ^
PGM-index/tuner/tuner.cpp:25:
PGM-index/tuner/tuner.hpp:176:34: error: invalid output constraint '=a' in asm
    __asm__ __volatile__("cpuid":"=a"(_), "=b"(_), "=c"(c), "=d"(_):"a"(0x80000006));
                                 ^
1 warning and 1 error generated.

**Comment by gvinciguerra** [comment]
Hi @chadbrewbaker and thanks for opening this issue.
It should be fixed now. Please, feel free to reopen this issue if the fix doesn't work for you. Thanks again :)
