### ISSUE TITLE
conflicts between sdsl and CompressPGM

### ISSUE THREAD

**Issue by authwork** [gvinciguerra/PGM-index#18]
Hello, I encounter an engineering issue.

That is the version conflicts between sdsl-lite and EliasFanoPGMIndex  in pgm_index_variants.hpp.
```
==============error====================
error: ‘const rank_1_type’ {aka ‘const class sdsl::rank_support_sd<1, sdsl::int_vector<1>, sdsl::select_support_mcl<1, 1>, sdsl::select_support_mcl<0, 1> >’} has no member named ‘pred’
  566 |         auto[r, origin] = rank.pred(k - first_key);
=====================================
```
I guess it is caused because current sdsl-lite does not support rank.pred.

```
../PGM-index/include/pgm/pgm_index_variants.hpp:570:28: error: could not convert ‘{pos, lo, hi}’ from ‘<brace-enclosed initializer list>’ to ‘pgm::ApproxPos’
  570 |         return {pos, lo, hi};
```
I compile sdsl-lite and the example code via std=c++17, but it still appears (very strange).

**Comment by gvinciguerra** [comment]
Thanks @authwork for pointing out this problem! It should be fixed now

**Comment by authwork** [comment]
@gvinciguerra Many thanks. It works now.
There are only a few minor issues:
1. 595 lines in ```pgm/pgm_index_variants.hpp```, m_v was not declared in this scope. I just comment it out to make it work because this is a assertment.
2. ```#include "pgm/pgm_index_variants.hpp"``` should be placed after including the headers from sdsl-lite. Reordering may cause redefined issue. This is just a reminder for others.
