### ISSUE TITLE
big floats indexing issue

### ISSUE THREAD

**Issue by mrsndmn** [gvinciguerra/PGM-index#23]
[**Notebook**](https://colab.research.google.com/drive/1trI8HxLTkD2RbAaVaUtan1urKJegZ30F?usp=sharing) to reproduce issue with pygm

Unfortunately I have not discovered a cause of the error. But I see this issue is only reproducible for floats that are bit enough.

**Comment by mrsndmn** [comment]
I updated the link. Now notebook should to be visible to everyone

**Comment by gvinciguerra** [comment]
Thanks @mrsndmn! 😉

I'll update the PGM-index submodule inside [pygm](https://github.com/gvinciguerra/PyGM) in the following days.
