### ISSUE TITLE
Scalability issue

### ISSUE THREAD

**Issue by authwork** [gvinciguerra/PGM-index#24]
Hello,@gvinciguerra. I have done a comparison betweem PGM-index with unordered_map (hash map) by using 
```
pgm::DynamicPGMIndex<__uint128_t, A> d_index; // A is a structure with multiple uint64_t
for(__uint128_t i=0; i<0xFFFFFFFFFFFFFFFF; i++){
	A a;
	a.a = (uint64_t)i;
	a.b = (uint64_t)2*i;
	a.c = (uint64_t)3*i;
	d_index.insert_or_assign(i, a);
}
A b;
A *c = &b;
for(__uint128_t i=0; i<0xFFFFFFFFFFFFFFFF; i++){
	auto iter = d_index.find(i);
	*c = iter->second;
	std::cout << b.a << " " << b.b << " " << b.c << std::endl;
}
```
The memory consumption of DynamicPGMIndex can achieve 98% and it will cause:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```
while the case using ```unordered_map ``` only has very low memory consumption.
Theoretical speaking, Hash map should use much more memory (pointers in linked list, RB tree etc)
Why this experiment show DynamicPGMIndex uses more memory? And how we solve it?

Another issue is mentioned in #17 How to achieve dynamic insertable set by using PGM index?

Many thanks

**Comment by gvinciguerra** [comment]
Hi @authwork. Your example requires *at least* `sizeof(__uint128_t)` * `0xFFFFFFFFFFFFFFFF` = 128 * (2^64-1) bytes, i.e.. 2.361 zettabytes of main memory. Are you sure it's not a hardware problem?

**Comment by authwork** [comment]
@gvinciguerra

**Comment by gvinciguerra** [comment]
If it crashes much faster it might be because it processes the inserts faster, and thus it reaches the memory limit of your machine in a shorter period of time. 

The swapping of memory depends on (the settings of) the operating system you are using. The crash is likely to happen when the program tries to malloc a space that is greater than the remaining space of the virtual memory (i.e. main memory + swap space).

**Comment by authwork** [comment]
It sounds. 
I will print the key to see when it crashes and do some comparison.

**Comment by authwork** [comment]
@gvinciguerra

**Comment by gvinciguerra** [comment]
This is a C++ question, have a look for example [here](https://isocpp.org/wiki/faq/freestore-mgmt#garbage-collector-basics).
I don't think you need this form of memory management. The structure takes responsibility for allocating and deallocating the memory it needs.
