### ISSUE TITLE
[Segmentation fault] Access structure in DynamicPGMIndex 

### ISSUE THREAD

**Issue by authwork** [gvinciguerra/PGM-index#25]
@gvinciguerra 

Hello, when I was doing my test, I found an issue about the DynamicPGMIndex.
```
        struct A{
	        uint64_t a, b, c;
        };

        pgm::DynamicPGMIndex<__uint128_t, A> d_index;
	for (uint64_t i = 0; i < 0xFFFFF; i++) {
		A a;
		a.a = i;
		a.b = 2 * i;
		a.c = 3 * i;
		d_index.insert_or_assign(i, a);
		if (i % 0x1FFFF == 0) {
			gettimeofday(&end, NULL);
			long time_len = 1000000 * (end.tv_sec - start.tv_sec) + (end.tv_usec - start.tv_usec);
			std::cout << (uint32_t)(i/0x1FFFF) << " costs " << time_len << std::endl;
			start = end;
		}
	}
	for (uint64_t i = 0; i < 0xFFFFF; i++) {
		auto iter = d_index.find(i);
		A b = iter->second;
		if(b.a != i || b.b != 2 * i|| b.c != 3 * i){
			printf("failed\n");
			return;
		}
	}
	printf("success\n");
```
gdb shows the fault happens when executing ```A b = iter->second;```. Does DynamicPGMIndex support a customized structure as its value type?

====================================
By the way, does PGM-index support GC? Is there any suggestions for memory management of using PGM-index.
Hash map indeed is very slow for inserting many data.

For example, in a case with PGM-index , VIRT become 2.5T, while RES is only 250G and cause allocate issue.
under the same case with ```unordered_map```, both VIRT and RSE are around 200G and finish the execution.

**Comment by gvinciguerra** [comment]
Under gcc 9.3.1, I don't get any segmentation fault with your code. Please provide a minimal reproducible example.

About garbage collection (GC), I answered [here](https://github.com/gvinciguerra/PGM-index/issues/24).

**Comment by authwork** [comment]
It might be because I forget to pull the updated version of PGM-Index. 

The last version works correct. @gvinciguerra Thanks for your help!
To fit PGM-index in the test, I update one place because PGM-index uses build-in sdsl.hpp, while our test also uses sdsl-lite lib. A conflict happens at 
```
PGM-index/include/pgm/pgm_index_variants.hpp:331:24: error: ‘class sdsl::int_vector<0>’ has no member named ‘back’
```
That's because sdsl-lite does not provide back function. I change it to be 
```
# in sdsl-lite's way
slopes_map[slopes_map.size()-1] = slopes_table[*std::prev(last_slope)];
```
And the program runs correct. Just a record.
