### ISSUE TITLE
multi-level PGM-index and its size

### ISSUE THREAD

**Issue by authwork** [gvinciguerra/PGM-index#26]
@gvinciguerra 
Hello, I have done a experiment to build multi-level PGM-index.
Why? I use it to support very large integer, like a 256-bit long integer.
Assume I have a uint256_t num, I set num[0] is a uint128_t with high 128 bits of num, num[1] is also a uint128_t with low 128 bits of num.
To index with PGM-index
```
typedef PGM-index<uint128_t, value> type1;
typedef PGM-index<uint128_t, type1 *> type2;
```
for insert.
I will first insert a type1 variable into type2, then insert the real value to the corresponding type1, such as:
```
type2 index2nd;
auto pp = index2nd.find(num[0]);
if(pp == index2nd.end()){
    type1 *pp2 = new type1();
    index2nd.insert_or_assign(num[0], pp2);
    pp2->insert_or_assign(num[1], value);
}
else{
    pp.second->insert_or_assign(num[1], value);
}
```
To calculate the size of the whole index:
```
uint64_t size = index2nd.size_in_bytes();
for (auto &e : index2nd) {
      size += e.second->size_in_bytes();
}
```
Does ```size``` correctly calculate the memory size of ```index2nd```?

**Comment by gvinciguerra** [comment]
Yep, the computation of overall memory (data + index) seems correct.

**Comment by authwork** [comment]
@gvinciguerra 
I found more surprising things:
I test the same program on different machines, but get totally different results by using PGM-index.
Using c++ 9, the index size is 205532009 bytes.
Using c++ 7, the index size is 309379385 bytes.

**Comment by gvinciguerra** [comment]
Could you check if you are using the master branch version of the PGM on both machines?

**Comment by authwork** [comment]
Yes, They are under then same version @ e2e82d77c50130c11941479301b9f835d2db1bb9.

**Comment by gvinciguerra** [comment]
Thanks for checking.

It's strange, under gcc version 9.3.1 and commit  e2e82d7 I get 309 MB as well. Indeed, the overall space of the `u64L` instances should be _at least_ `Max_J * Max_i * (sizeof(uint64_t) + sizeof(T)) =  0x8F * 0xFFFF * (8 + 24) =` [300 MB](https://www.wolframalpha.com/input/?i=+0x8F+*+0xFFFF+*+%288+%2B+24%29+bytes).

Could you check the output of `gcc -v`?

**Comment by authwork** [comment]
It is ```gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)```

I should backup previous code, when I reset the head to commit e2e82d7, I found I cannot reproduce the result of 205M, although I used to get this result for multiple times in the past.
