### ISSUE TITLE
PGMIndex return incorrect range on books dataset

### ISSUE THREAD

**Issue by marcelmaltry** [gvinciguerra/PGM-index#30]
Hi,

for some values of epsilon, PGM returns incorrect ranges on the books dataset from SOSD.

Dataset: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/JGVF9A/A6HDNT&version=10.0

Code to reproduce the issue:
```c++
#include <vector>
#include <fstream>
#include <iostream>

#include "pgm/pgm_index.hpp"


template<typename Key>
std::vector<Key> load_data(const std::string &filename) {
    using key_type = Key;

    /* Open file. */
    std::ifstream in(filename, std::ios::binary);
    if (!in.is_open())
        exit(EXIT_FAILURE);

    /* Read number of keys. */
    uint64_t n_keys;
    in.read(reinterpret_cast<char*>(&n_keys), sizeof(uint64_t));

    /* Initialize vector. */
    std::vector<key_type> data;
    data.resize(n_keys);

    /* Read keys. */
    in.read(reinterpret_cast<char*>(data.data()), n_keys * sizeof(key_type));
    in.close();

    return data;
}

int main(int argc, char *argv[])
{
    /* Load keys. */
    auto keys = load_data<uint64_t>("data/books_200M_uint64");
    std::cout << "keys loaded" << std::endl;

    /* Build PGM. */
    const int epsilon = 2048;
    pgm::PGMIndex<uint64_t, epsilon> pgm(keys);
    std::cout << "pgm built" << std::endl;

    /* Lookup all keys. */
    for (std::size_t i = 0; i != keys.size(); ++i) {
        auto key = keys.at(i);
        auto range = pgm.search(key);
        if (range.lo > i or range.hi < i) {
            std::cout << "key not in range\n"
                      << "key: " << key << '\n'
                      << "pos: " << i << '\n'
                      << "lo: " << range.lo << '\n'
                      << "hi: " << range.hi << '\n'
                      << std::endl;
        }
    }
}
```

Output for `epsilon=2048`:
```
...
key not in range
key: 880841552717461696
pos: 47236183
lo: 47236184
hi: 47240282

key not in range
key: 880842439537799360
pos: 47236231
lo: 47236232
hi: 47240330
```
Output for `epsilon=16384`:
```
...
key not in range
key: 1154823330085936896
pos: 61887138
lo: 61887141
hi: 61919911

key not in range
key: 1154823338493908224
pos: 61887139
lo: 61887141
hi: 61919911

key not in range
key: 1154823341621615232
pos: 61887140
lo: 61887141
hi: 61919911
```

**Comment by gvinciguerra** [comment]
Hi @marcelmaltry, I didn't get any errors. Are you using the latest commit?

**Comment by marcelmaltry** [comment]
I am using the latest commit and the latest v10 of the `books64` dataset.

I am having this issue on two separate machines:
1. running macOS, compiling with Apple clang 12.0.5
2. running ArchLinux, compiling with clang 11.1.0

I only get the following warning during compilation that should, however, not affect the computations.
```
In file included from ../../third_party/PGM-index/include/pgm/pgm_index.hpp:18:
../../third_party/PGM-index/include/pgm/piecewise_linear_model.hpp:31:9: warning: Compilation with -fopenmp is optional but recommended [-W#pragma-messages]
#pragma message ("Compilation with -fopenmp is optional but recommended")
        ^
```

**Comment by gvinciguerra** [comment]
Thanks for the additional info @marcelmaltry. I can't reproduce it with either clang 12.0.1 or gcc 9.3.1 running on CentOS 7.9
Could you try to clean up your build environment? Maybe there's some cached code...

The warning you are seeing indeed is related to the parallel construction of `PGMIndex` and the other classes in this library, and it doesn't affect the queries.

**Comment by marcelmaltry** [comment]
The issue remains. Here is what I did.

* Freshly clone this repository
* Copy the `books` dataset to `data/`
* Put the exact code from above into a file `mytest.cpp`
* Put the following line at the end of `CMakeLists.txt`: `add_executable(mytest mytest.cpp)`
* Build and run the binary as follows:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
cd ..
build/mytest
```

**Comment by gvinciguerra** [comment]
Could you try adding this line at the end of your edited `CMakeLists.txt`?

```cmake
target_link_libraries(mytest pgmindexlib)
```

**Comment by marcelmaltry** [comment]
Doing this gives me other incorrect intervals:
```
keys loaded
pgm built
key not in range
key: 457942223912412576
pos: 24559033
lo: 24559034
hi: 24563132

key not in range
key: 457942249603350848
pos: 24559034
lo: 24559036
hi: 24563134

key not in range
key: 457942261840454048
pos: 24559035
lo: 24559036
hi: 24563134

key not in range
key: 927060091745337984
pos: 49712908
lo: 49712909
hi: 49717007
```

**Comment by gvinciguerra** [comment]
Maybe it's a precision issue. What happens if you replace:

https://github.com/gvinciguerra/PGM-index/blob/d01e4bd8f601171f366cc43edfb954b3d48b420a/include/pgm/pgm_index.hpp#L255

with

```cpp
        auto pos = int64_t(slope * double(k - key)) + intercept;
```

**Comment by marcelmaltry** [comment]
This appears to resolve all but the last issues from before.
```
keys loaded
pgm built
key not in range
key: 927060091745337984
pos: 49712908
lo: 49712909
hi: 49717007
```

**Comment by gvinciguerra** [comment]
Ok, so different CPUs give different floating point operations results. 

What about adding `fesetround(FE_DOWNWARD);` at the beginning of your main function (it needs `#include <cfenv>`)?

**Comment by marcelmaltry** [comment]
With this I no longer get the issue.

However, I wonder why that is? To my understanding, IEEE 754 should make floating point computations portable across CPUs.

**Comment by gvinciguerra** [comment]
> However, I wonder why that is? To my understanding, IEEE 754 should make floating point computations portable across CPUs.

To my surprise too it is hard to get consistent floating point results on different CPUs and compilers (see e.g. [here](https://stackoverflow.com/questions/21212326/floating-point-arithmetic-and-reproducibility), [here](https://stackoverflow.com/questions/20963419/cross-platform-floating-point-consistency) or [here](https://stackoverflow.com/questions/328622/how-deterministic-is-floating-point-inaccuracy)) 🙁
