### ISSUE TITLE
Questions about Error Bound 

### ISSUE THREAD

**Issue by min-guk** [gvinciguerra/PGM-index#41]
I was very impressed with your paper. 
I don't know if I understood the research paper well, but I ask because error bounds are quite different with what I understand.

1. 
What is inclusive search error bound for positive search?
I thought search error bound for positive search is [p-e, p+e], but it seems [p-e, p+e+1].
Therefore it seems bottom segments returns search range satisfying "key_p-e <= positive lookup_key <= key_p+e+1".

2. 
According your code, the search range for bottom segment is [p-e, p+e+2)  and search range for upper(not bottom) segment is (p-e-1, p+e+2). Is it because pgm-index have to select a segment with a key less than the lookup key in upper level and optimal-plr returns search range that is not less than unpresent key?

3.
What is search error bound for negative-search(searching missing key) to get same result of std::lower_bound()?

In the middle, I accidentally uploaded the question before I finished writing it.
Sorry for so many questions, but I really want to understand your research well.
Thank you.

**Comment by gvinciguerra** [comment]
Hi, and thanks for your interest.

1. The +1 is because, for an implementation choice, the intercepts are truncated and stored as integers, which increases the error on one side by 1.
2. Correct.
3. [p-e, p+e+1].

**Comment by min-guk** [comment]
Thank you for your kind reply.
I have a few more questions, and I'd be grateful if you could answer them.

1.
The search range of the pgm-index is returned as exclusive rather than inclusive on one side. Why?
If we narrow the error range to even 1, can't we expect better performance from std::lower_bound()?
Is there any particular reason for returning one side as exclusive?

2. 
The code comment explains that the error range is 2e+1, but in fact, strictly speaking, isn't it 2e+2 instead of 2e+1?

Thank you.

**Comment by gvinciguerra** [comment]
1. The right side of the returned range is exclusive to conform to the semantic of the begin/end iterators in C++.
2. Yep, because of the implementation choice stated in my last comment.

**Comment by min-guk** [comment]
Thanks!
