### ISSUE TITLE
No install instructions in CMakeLists.txt + missing PGMConfig.cmake / pgm-config.cmake

### ISSUE THREAD

**Issue by brechtsanders** [gvinciguerra/PGM-index#42]
Any plans to add proper installation instructions to CMakeLists.txt?

Also, when trying to build columnar CMake returns the following error:
```
ninja: build stopped: subcommand failed.
CMake Error at cmake/GetPGM.cmake:39 (find_package):
  Could not find a package configuration file provided by "PGM" with any of
  the following names:

    PGMConfig.cmake
    pgm-config.cmake

  Add the installation prefix of "PGM" to CMAKE_PREFIX_PATH or set "PGM_DIR"
  to a directory containing one of the above files.  If "PGM" provides a
  separate development package or SDK, be sure it has been installed.
```

So, these files should also be installed when installing PGM-index.

**Comment by gvinciguerra** [comment]
Hi @brechtsanders, I believe you should refer to the installation instructions in the [proper repo](https://github.com/manticoresoftware/columnar), where [GetPGM.cmake](https://github.com/manticoresoftware/columnar/blob/master/cmake/GetPGM.cmake) is defined.
