### ISSUE TITLE
Paper - Documentation

### ISSUE THREAD

**Issue by alessiosavi** [gvinciguerra/PGM-index#5]
Seems that the publication over https://arxiv.org/abs/1910.06169 can not be reached. It's possible to upload the paper here?

**Comment by gvinciguerra** [comment]
Yes, it seems that arXiv is [temporarily offline](https://twitter.com/arxiv/status/1192467597054361606), but you can grab a copy also from [ResearchGate](https://www.researchgate.net/publication/336551128_The_PGM-index_a_multicriteria_compressed_and_learned_approach_to_data_indexing).

Thank you for your interest in our paper 😉
