### ISSUE TITLE
Question: About possible support of float type as Key

### ISSUE THREAD

**Issue by yangzq50** [gvinciguerra/PGM-index#52]
Before commit 6e2710e , I used to be able to use float type as key and build a PGM index.
In my simple test, the PGM index seems to work with float types.
In commit 6e2710e , the following ` std::make_unsigned_t ` code limits the key type to integral types.

I am curious that whether float types are supposed to be supported?
 
https://github.com/gvinciguerra/PGM-index/blob/5e4c7086164d0f04ea4062f762f296dbd070ef40/include/pgm/pgm_index.hpp#L274

**Comment by gvinciguerra** [comment]
Fixed, thanks
