### ISSUE TITLE
How is the compression of the intercept calculated

### ISSUE THREAD

**Issue by xq245** [gvinciguerra/PGM-index#57]
In the fourth chapter of the paper, it is mentioned that the intercept needs m log(n/m)+1.92m + o(m) bits to store. I have two questions, one is how 1.92m was calculated, and the other is how m log(n/m) was obtained. On the second question, the answer I got from my search was "In the case of PGM indexing, n keys are divided into m line segments. Thus, each line segment contains approximately n/m keys. This means that if we are looking for a particular key in a line segment, we need to be able to represent n/m different values. This is the reason why the intercept of each line segment should be expressed in log(n/m) bits ."
    if this answer is correct, does it mean that when you calculate the space usage, you estimate the worst case and reserve this part of the space for the built index before the index is built, or because when calculating the PLA model, the intercept is updated with the expansion of the convex hull? There may be log(n/m) possibilities during the intercept update of each line segment, so each line segment requires log(n/m) bits to represent these intercepts. These are my guesses, I am a beginner, if you can take time out of your busy schedule to help me answer questions, I would be very grateful!

**Comment by gvinciguerra** [comment]
Hi, your guess is not correct. Have a look at paper [25], which should answer both your questions
