### ISSUE TITLE
Recommendations for large list of strings?

### ISSUE THREAD

**Issue by mySYSMON** [gvinciguerra/PGM-index#8]
I tried to convert my 125 million domains to a unique set of integers but the integer values exceeded the max for 64bit ints.  Does anyone know a way to solve this?  Maybe something obvious I am not seeing.

**Comment by gvinciguerra** [comment]
Hi @mySYSMON,

The PGM-index is made for integers that fit into a computer word. So I’m not sure it’s the right tool for your problem.

In theory, you could:

1. Store the domains into a sorted array _A_.
2. Create a mapping from strings to `uint128_t` integers that works for a prefix of up to log_30(2^128) = 27 characters of a domain.*
3. Build the PGM-index on the integers returned by the mapping above applied to the strings in _A_ truncated to 27 characters.

Then, at query time, you would:

1. Use PGM-index to get the starting position _P_ into _A_ of the domains that share a prefix (of up to 27 characters) with the given domain.
2. Scan _A_ (or better, use an exponential search) starting from the position _P_ to find the domain you are looking for.

But this is could be a contrived solution for your problem. For long strings, you may want to use a hash table or a trie instead, depending on the kind of searches you want to do. E.g. If they are exact matches then use a hash table (e.g. Python’s `set` or C++’s `std::unordered_set`).

Hope this helps.

*I’m assuming standard domains (and not [IDNs](https://en.wikipedia.org/wiki/Internationalized_domain_name)) that use ASCII letters, digits, hyphens and dots, so an alphabet of 30 characters.

**Comment by Get-MEOW** [comment]
Wow, awesome and very helpful answer.  Thank you!

**Comment by mySYSMON** [comment]
great answer, thanks!

**Comment by gvinciguerra** [comment]
My pleasure 😊
